### ISSUE TITLE
Two nodes on same domain?

### ISSUE THREAD

**Issue by geosphere** [thefederationinfo/the-federation.info#168] opened 2018-12-08 23:08 UTC
I have two different services (socialhome and matrix) on the same domain. It is possible to register the second node?

**Comment by Mikaela** [comment] 2018-12-09 07:12
I think this might be a duplicate of https://github.com/thefederationinfo/the-federation.info/issues/135#issuecomment-443312536 (or at least I was never told otherwise).

**Comment by jaywink** [comment] 2018-12-09 16:11
Currently, unfortunately, the host is a unique key so registering a domain name both as for example Diaspora and XMPP, or Socialhome and Matrix, is not possible. I'll naturally have to change that, because now that both Matrix and XMPP have started to be registered, they often run on the same domain name as some other service. This isn't the case with the more social network type platforms.

Thanks for raising this.

**Closed** 2022-07-17 16:37 UTC
Labels: bug, help wanted
